version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: lms-backend
    environment:
      DB_HOST: host.docker.internal
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_DATABASE: lms_db
      JWT_SECRET: your-super-secret-jwt-key-here-change-this-in-production
      JWT_EXPIRES_IN: 7d
      PORT: 3000
      NODE_ENV: development
      UPLOAD_DEST: ./uploads
      MAX_FILE_SIZE: 10485760
      # Allow all localhost origins for development
      CORS_ORIGIN: "http://localhost:3001,http://127.0.0.1:3001,http://frontend:80"
    ports:
      - "3000:3000"
    volumes:
      - ./backend/uploads:/app/uploads
    networks:
      - lms-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.scientific
      args:
        # API URL now hardcoded in api.ts, but keep this for consistency
        REACT_APP_API_URL: http://localhost:3000/api
    container_name: lms-frontend
    ports:
      - "3001:80"
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - lms-network
    restart: unless-stopped

networks:
  lms-network:
    driver: bridge